export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_NOW_PLAYING_MOVIES = "GET_NOW_PLAYING_MOVIES";
export const GET_MOVIES_BY_SEARCH = "GET_MOVIES_BY_SEARCH";
export const SAVE_SEARCH_KEYWORD = "SAVE_SEARCH_KEYWORD";
export const GET_VIDEOS_MOVIE_ID = "GET_VIDEOS_MOVIE_ID";
